import type { Layouts } from "react-grid-layout";

export const defaultLayouts: Layouts = {
  lg: [
    { i: "today", x: 0, y: 0, w: 6, h: 5 },
    { i: "alerts", x: 6, y: 0, w: 6, h: 5 },
    { i: "journal", x: 0, y: 5, w: 6, h: 7 },
    { i: "calendar", x: 6, y: 5, w: 6, h: 5 },
    { i: "career", x: 6, y: 10, w: 6, h: 5 },
    { i: "memo", x: 0, y: 12, w: 6, h: 5 },
    { i: "study", x: 0, y: 17, w: 6, h: 6 },
    { i: "health", x: 6, y: 15, w: 3, h: 4 },
    { i: "money", x: 9, y: 15, w: 3, h: 4 },
    { i: "mood", x: 6, y: 19, w: 3, h: 4 },
  ],
  md: [
    { i: "today", x: 0, y: 0, w: 6, h: 5 },
    { i: "alerts", x: 6, y: 0, w: 6, h: 5 },
    { i: "journal", x: 0, y: 5, w: 6, h: 7 },
    { i: "calendar", x: 6, y: 5, w: 6, h: 5 },
    { i: "career", x: 6, y: 10, w: 6, h: 5 },
    { i: "memo", x: 0, y: 12, w: 6, h: 5 },
    { i: "study", x: 0, y: 17, w: 6, h: 6 },
    { i: "health", x: 6, y: 15, w: 6, h: 4 },
    { i: "money", x: 6, y: 19, w: 6, h: 4 },
    { i: "mood", x: 0, y: 23, w: 6, h: 4 },
  ],
  sm: [
    { i: "today", x: 0, y: 0, w: 4, h: 5 },
    { i: "alerts", x: 0, y: 5, w: 4, h: 5 },
    { i: "journal", x: 0, y: 10, w: 4, h: 8 },
    { i: "calendar", x: 0, y: 18, w: 4, h: 5 },
    { i: "career", x: 0, y: 23, w: 4, h: 5 },
    { i: "memo", x: 0, y: 28, w: 4, h: 5 },
    { i: "study", x: 0, y: 33, w: 4, h: 6 },
    { i: "health", x: 0, y: 39, w: 4, h: 4 },
    { i: "money", x: 0, y: 43, w: 4, h: 4 },
    { i: "mood", x: 0, y: 47, w: 4, h: 4 },
  ],
};